### ISSUE TITLE
[BUG] Nil pointer exception

### ISSUE THREAD

**Issue by rfranzke** [gardener/dependency-watchdog#26]
**Describe the bug:**
We've observed some nil pointer exceptions in DWD that should ideally be prevented.

**Expected behaviour:**
DWD should run smoothly and handle errors appropriate instead of panicking.

**How To Reproduce (as minimally and precisely as possible):**
No concrete steps, sorry.

**Logs:**
```
I0807 16:09:17.312579       1 scaler.go:227] Starting the probe in the namespace shoot--foo--bar: &{shoot-kube-apiserver 0xc0000dea80 [0xc0000dea00]}
E0807 16:09:17.312959       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 42909 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x147fc60, 0x232d7c0)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x147fc60, 0x232d7c0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/gardener/dependency-watchdog/pkg/scaler.(*prober).doProbe(0xc017b84400, 0xc013a8b580, 0x39, 0x0, 0x0, 0xc017b844c0)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/pkg/scaler/prober.go:304 +0x57
github.com/gardener/dependency-watchdog/pkg/scaler.(*prober).probe(0xc017b84400, 0x1893de0, 0xc00068e7c0, 0x1, 0xc000585ba0)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/pkg/scaler/prober.go:263 +0x13c
github.com/gardener/dependency-watchdog/pkg/scaler.(*prober).run.func1(0x1893de0, 0xc00068e7c0)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/pkg/scaler/prober.go:212 +0x88
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000585cd0)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000585cd0, 0x18585a0, 0xc000ff8210, 0xc0147dcf01, 0xc0146917a0)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000585cd0, 0x6fc23ac00, 0x3fc999999999999a, 0x48a801, 0xc0146917a0)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0xe2
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x1893de0, 0xc00068e7c0, 0xc000585d98, 0x6fc23ac00, 0x3fc999999999999a, 0xc0000fee01)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0xa6
github.com/gardener/dependency-watchdog/pkg/scaler.(*prober).run(0xc017b84400, 0xc014691740, 0x0, 0x0)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/pkg/scaler/prober.go:202 +0x20d
github.com/gardener/dependency-watchdog/pkg/scaler.(*prober).tryAndRun(0xc017b84400, 0xc000585f78, 0x1b, 0x188f260)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/pkg/scaler/prober.go:170 +0x28b
github.com/gardener/dependency-watchdog/pkg/scaler.(*Controller).processNamespace.func1(0xc000120120, 0xc00042c000, 0xc01613c440, 0x1b, 0xc00042c000)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/pkg/scaler/scaler.go:226 +0x1ad
created by github.com/gardener/dependency-watchdog/pkg/scaler.(*Controller).processNamespace
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/pkg/scaler/scaler.go:217 +0x114
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb8 pc=0x12e12d7]

goroutine 42909 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x147fc60, 0x232d7c0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/gardener/dependency-watchdog/pkg/scaler.(*prober).doProbe(0xc017b84400, 0xc013a8b580, 0x39, 0x0, 0x0, 0xc017b844c0)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/pkg/scaler/prober.go:304 +0x57
github.com/gardener/dependency-watchdog/pkg/scaler.(*prober).probe(0xc017b84400, 0x1893de0, 0xc00068e7c0, 0x1, 0xc000585ba0)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/pkg/scaler/prober.go:263 +0x13c
github.com/gardener/dependency-watchdog/pkg/scaler.(*prober).run.func1(0x1893de0, 0xc00068e7c0)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/pkg/scaler/prober.go:212 +0x88
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000585cd0)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000585cd0, 0x18585a0, 0xc000ff8210, 0xc0147dcf01, 0xc0146917a0)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000585cd0, 0x6fc23ac00, 0x3fc999999999999a, 0x48a801, 0xc0146917a0)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0xe2
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x1893de0, 0xc00068e7c0, 0xc000585d98, 0x6fc23ac00, 0x3fc999999999999a, 0xc0000fee01)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0xa6
github.com/gardener/dependency-watchdog/pkg/scaler.(*prober).run(0xc017b84400, 0xc014691740, 0x0, 0x0)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/pkg/scaler/prober.go:202 +0x20d
github.com/gardener/dependency-watchdog/pkg/scaler.(*prober).tryAndRun(0xc017b84400, 0xc000585f78, 0x1b, 0x188f260)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/pkg/scaler/prober.go:170 +0x28b
github.com/gardener/dependency-watchdog/pkg/scaler.(*Controller).processNamespace.func1(0xc000120120, 0xc00042c000, 0xc01613c440, 0x1b, 0xc00042c000)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/pkg/scaler/scaler.go:226 +0x1ad
created by github.com/gardener/dependency-watchdog/pkg/scaler.(*Controller).processNamespace
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/pkg/scaler/scaler.go:217 +0x114
```

**Comment by amshuman-kr** [comment]
Thanks for reporting. I will add the necessary check.

**Comment by unmarshall** [comment]
@rfranzke do you still see this problem? Last comment from amshuman states that he will add necessary check. In the mean time the code has undergone several changes changing the line numbers which makes it hard to know where the nil pointer dereference now occurs.

**Comment by unmarshall** [comment]
/close
Not seen this issue for some time.
