### ISSUE TITLE
invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/dependency-watchdog#27]
**Describe the bug:**

```
$ k -n garden get po dependency-watchdog-probe-5699594f8b-z8cd4
NAME                                         READY   STATUS    RESTARTS   AGE
dependency-watchdog-probe-5699594f8b-z8cd4   1/1     Running   4          101m
```

```
$ k -n garden logs dependency-watchdog-probe-5699594f8b-z8cd4 -p

I0924 09:18:44.628382       1 scaler.go:72] Update event on cluster: shoot--it--tmghj-0da
E0924 09:18:44.715691       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 62 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x18bbae0, 0x2b49eb0)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x18bbae0, 0x2b49eb0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/gardener/dependency-watchdog/pkg/scaler.shootHibernationStateChanged(0xc000972bc0, 0xc0000b8d00, 0xa)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/pkg/scaler/utils.go:88 +0x341
github.com/gardener/dependency-watchdog/pkg/scaler.NewController.func1(0x1aa80e0, 0xc000972bc0, 0x1aa80e0, 0xc0000b8d00)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/pkg/scaler/scaler.go:79 +0xff
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/client-go/tools/cache/controller.go:205
k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x0, 0x0, 0x0)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/client-go/tools/cache/shared_informer.go:656 +0x188
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc00dcc9dd8, 0x0, 0x0)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:292 +0x51
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/client-go/tools/cache/shared_informer.go:652 +0x79
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0003e6740)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00dcc9f40, 0xdf8475800, 0x0, 0x42da01, 0xc0005c6cc0)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000367a00)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/client-go/tools/cache/shared_informer.go:650 +0x9b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0004c18e0, 0xc00035d290)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x59
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17046a1]

goroutine 62 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x18bbae0, 0x2b49eb0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/gardener/dependency-watchdog/pkg/scaler.shootHibernationStateChanged(0xc000972bc0, 0xc0000b8d00, 0xa)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/pkg/scaler/utils.go:88 +0x341
github.com/gardener/dependency-watchdog/pkg/scaler.NewController.func1(0x1aa80e0, 0xc000972bc0, 0x1aa80e0, 0xc0000b8d00)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/pkg/scaler/scaler.go:79 +0xff
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/client-go/tools/cache/controller.go:205
k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x0, 0x0, 0x0)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/client-go/tools/cache/shared_informer.go:656 +0x188
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc00dcc9dd8, 0x0, 0x0)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:292 +0x51
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/client-go/tools/cache/shared_informer.go:652 +0x79
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0003e6740)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00dcc9f40, 0xdf8475800, 0x0, 0x42da01, 0xc0005c6cc0)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000367a00)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/client-go/tools/cache/shared_informer.go:650 +0x9b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0004c18e0, 0xc00035d290)
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x59
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/tmp/build/80754af9/git-gardener_dependency-watchdog-master_master/tmp/src/github.com/gardener/dependency-watchdog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
```

**Anything else we need to know?**:

dependency-watchdog version: `v0.6.0`

**Comment by amshuman-kr** [comment]
Ismail. I am already working on the PR.

**Comment by amshuman-kr** [comment]
@ialidzhikov I am already working on the PR.

**Comment by amshuman-kr** [comment]
Will file it shortly.

**Comment by amshuman-kr** [comment]
@ialidzhikov Here it is https://github.com/gardener/dependency-watchdog/pull/28
